project:
  type: book


book:
  title: "技術文書プロジェクト"
  author: "Ramses Yok"
  date: "2026/3/29"
  date-format: "YYYY/M/D"
  chapters:
    - index.qmd
    - tables.qmd

format:
  # Typst(PDF)出力の設定
  typst:
    number-sections: true
    toc: true
    toc-depth: 3
    template: template.typ
    docnumber: "TECH-2026-001"
    mainfont: "Meiryo"
    monofont: "Consolas"
    fontsize: 10.5pt

  # HTML出力の設定
  html:
    number-sections: true
    toc: true

# 言語設定
lang: ja


